honor/urls.py
from django.urls import path

from . import views

app_name = "honor"
urlpatterns = [
    #path("", views.IndexView.as_view(), name="index"),
    path("", views.login, name="login"),
    path("home/", views.index, name="index"),
    path("report/", views.report, name="report"),
    path("submit_report/", views.submit_report, name="submit_report"),
    path("edit_report/", views.edit_report, name="edit_report"),
    path("submitted/", views.submitted_view, name="submitted"),
    path("<int:report_id>/reportDisplay/", views.reportDisplay_view, name="reportDisplay"),
    path("<int:report_id>/reportEdit/", views.reportEdit_view, name="reportEdit"),
    path("logout_view/", views.logout_view, name = "logout_view"),
    path('create_task/', views.create_task, name='create_task'),
    path('socialapp_check', views.socialapp_check, name='socialapp_check'),
    path("<int:report_id>/add_admin_comments", views.add_admin_comments, name = "add_admin_comments"),
    path("<int:report_id>/resolve", views.resolve, name = "resolve"),
    path("<int:report_id>/delete_report", views.delete_report, name = "delete_report"),
    path("continue_anonymously/", views.continue_anonymously, name = "continue_anonymously")
]

honorsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("honor/", include("honor.urls")),
    path("", include("allauth.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("honor.urls"))
]

honor/models.py
import enum

from django.db import models
from django.contrib.auth.models import User
import django.utils.timezone

class Task(models.Model):
    description = models.TextField(max_length=200, null=True)

    def __str__(self):
        return self.description

# citation: https://medium.com/@bencleary/using-enums-as-django-model-choices-96c4cbb78b2e
class ResolutionStatus(enum.IntEnum):
    NEW = 1
    IN_PROGRESS = 2
    RESOLVED = 3

    @classmethod
    def choices(cls):
        return [(key.value, key.name) for key in cls]


class Report(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    session_id = models.CharField(max_length=40, blank=True)
    timeStamp = models.DateTimeField(default=django.utils.timezone.now)
    nameOfOffender = models.CharField(max_length=200)
    className = models.CharField(max_length=300)
    location = models.CharField(max_length=300)
    description = models.TextField()
    file = models.FileField(upload_to='report/', blank=True, null=True)
    addInfo = models.TextField()
    status = models.IntegerField(choices=ResolutionStatus.choices(), default=ResolutionStatus.NEW)
    admin_comments = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.nameOfOffender} {self.className} {self.location} {self.description} {self.file}"

    def get_status(self):
        return ResolutionStatus(self.status).name

honor/forms.py
from django import forms
from .models import Task
from .models import Report

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['description']

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['nameOfOffender', 'description']

honor/views.py
import cgi
from datetime import datetime

import boto3
from django import template
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.template import loader
from django.views import generic

from django.shortcuts import render, redirect
from django.contrib.sessions.models import Session
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .models import Task, ResolutionStatus
from .forms import TaskForm, ReportForm
from django.core.files.storage import default_storage
from allauth.socialaccount.models import SocialApp

from honor.models import Report


# Create your views here.
# class IndexView(generic.ListView):
# template_name = "honor/index.html"
# def get_queryset(self):
#     return
def index(request):
    template = loader.get_template("honor/index.html")
    # context = {"title":"honor"}
    return render(request, "honor/index.html")


def report(request):
    template = loader.get_template("honor/report.html")
    return render(request, "honor/report.html")


def submit_report(request):
    if not request.session.session_key:
        request.session.create()
    print(request.session.session_key)
    # getting the information inputted into the report fields #
    nameOfOffender = request.POST.get("nameOfOffender")
    className = request.POST.get("className")
    location = request.POST.get("location")
    description = request.POST.get("description")
    addInfo = request.POST.get("addInfo")
    file = request.FILES.get("file")
    file_key = None
    #admin_comments = request.POST.get("admin_comments")

    timeStamp = datetime.now()

    print(nameOfOffender, className, location, description, addInfo)
    if not nameOfOffender and not className and not location and not description and not addInfo and not file:
        # if user didn't input any information into the fields
        return render(request, "honor/report.html", {"error_message": "Please fill out atleast one field"})
        # return HttpResponseRedirect(reverse("polls:submitted", args=(question_id,title)))
    else:
        if request.user.is_authenticated:
            filedReport = Report.objects.create(user=request.user, nameOfOffender=nameOfOffender, className=className, location=location, description=description, addInfo=addInfo, file=file)
        else:
            filedReport = Report.objects.create(session_id=request.session.session_key, nameOfOffender=nameOfOffender, className=className, location=location, description=description, addInfo=addInfo,)


        return render(request, "honor/index.html")
def edit_report(request):
    # getting the information inputted into the report fields #
    reportId = request.POST.get("Id")
    nameOfOffender = request.POST.get("nameOfOffender")
    className = request.POST.get("className")
    location = request.POST.get("location")
    description = request.POST.get("description")
    addInfo = request.POST.get("addInfo")
    existing_report = Report.objects.get(id=reportId)  # Replace `report_id` with the actual ID of the report you want to edit

    timeStamp = datetime.now()
    files = request.FILES.getlist("file")

    print(nameOfOffender, className, location, description, addInfo)
    if not nameOfOffender and not className and not location and not description and not addInfo:
        # if user didn't input any information into the fields
        return render(request, "honor/reportEdit.html", {"report": existing_report, "error_message": "Please fill out atleast one field"})
        # return HttpResponseRedirect(reverse("honor:reportEdit", args=(reportId,)))
    else:
        existing_report.nameOfOffender = nameOfOffender
        existing_report.className = className
        existing_report.location = location
        existing_report.description = description
        existing_report.addInfo = addInfo
        existing_report.status = ResolutionStatus.NEW
        existing_report.save()
        # filedReport = Report.objects.create(nameOfOffender=nameOfOffender, className=className, location=location, description=description, addInfo=addInfo)

        # for file in files:
        #     reportFile = File.objects.create(report=filedReport, file=file)

        # return render(request, "honor/"+reportId+"/reportDisplay.html")
        return HttpResponseRedirect(reverse("honor:reportDisplay", args=(reportId,)))

import boto3
from .forms import ReportForm

#Citation: https://www.hacksoft.io/blog/direct-to-s3-file-upload-with-django
def submitted_view(request):
    if request.method == 'POST':
        form = ReportForm(request.POST, request.FILES)
        if form.is_valid():
            attachment_file = request.FILES.get('attachment') 
            if attachment_file:
                s3 = boto3.client('s3')
                bucket_name = 'honor-bucket-v2'
                s3.upload_fileobj(attachment_file, bucket_name)
            report = Report(
                nameOfOffender=form.cleaned_data['nameOfOffender'],
                description=form.cleaned_data['description'],
            )
            report.save()

            return redirect('success_page')
    else:
        form = ReportForm()
    
    if request.user.groups.filter(name="power-user").exists():
        report_list = Report.objects.all()
    elif request.user.is_authenticated:
        report_list = Report.objects.filter(user=request.user)
    else:
        report_list = Report.objects.filter(session_id=request.session.session_key)

    context = {
        'report_list': report_list,
        'form': form,
    }
    return render(request, 'honor/submitted.html', context)


def reportDisplay_view(request, report_id): #,report_number
    # Retrieve report list
    report = Report.objects.get(id=report_id)

    if request.user.groups.filter(name="power-user").exists() and report.status == ResolutionStatus.NEW:
        print("updating status")
        report.status = ResolutionStatus.IN_PROGRESS
        report.save()

    context = {
        'report': report,
        'report_status': report.get_status(),
        #'report_number': report_number
    }
    return render(request, 'honor/reportDisplay.html', context)
def reportEdit_view(request, report_id):
    # Retrieve report list
    report = Report.objects.get(id=report_id)

    context = {
        'report': report,
        'report_status': report.get_status()
    }
    return render(request, 'honor/reportEdit.html', context)

#Citation: https://www.youtube.com/watch?v=yO6PP0vEOMc
def login(request):
    template = loader.get_template("honor/login.html")
    return render(request, "honor/login.html")

#Citation: https://www.youtube.com/watch?v=yO6PP0vEOMc
def logout_view(request):
    #if request.user.is_authenticated:
    logout(request)
    return redirect("/")

# THIS METHOD IS FOR TESTING
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            # Process the form data if needed
            form.save()
            # Clear the form for a new task
            form = TaskForm()
    else:
        form = TaskForm()

    return render(request, 'honor/create_task.html', {'form': form})


# THIS METHOD IS FOR TESTING
def socialapp_check(request):
    try:
        google_app = SocialApp.objects.get(provider='google')
        context = {'google_app_exists': True}
    except SocialApp.DoesNotExist:
        context = {'google_app_exists': False}

    return render(request, 'honor/socialapp_check.html', context)

def add_admin_comments(request, report_id):
    report = Report.objects.get(id=report_id)
    report.admin_comments = request.POST.get('comments', '')
    # report.status = ResolutionStatus.RESOLVED
    report.save()

    #TODO: this is a placeholder, redirect to a confirmation page or whatever
    context = {
        'report': report,
        'report_status': report.get_status()
    }
    return render(request, 'honor/reportDisplay.html', context)

def resolve(request, report_id):
    report = Report.objects.get(id=report_id)
    report.status = ResolutionStatus.RESOLVED
    report.save()

    #TODO: this is a placeholder, redirect to a confirmation page or whatever
    context = {
        'report': report,
        'report_status': report.get_status()
    }
    return render(request, 'honor/reportDisplay.html', context)

def delete_report(request, report_id):
    report = Report.objects.get(id=report_id)
    report.delete()

    if request.user.groups.filter(name="power-user").exists():
        report_list = Report.objects.all()
    elif request.user.is_authenticated:
        report_list = Report.objects.filter(user=request.user)
    else:
        report_list = Report.objects.filter(session_id=request.session.session_key)

    context = {
        'report_list': report_list,
    }
    return render(request, 'honor/submitted.html', context)


def continue_anonymously(request):
    logout(request)
    return render(request, 'honor/index.html')

honor/templates/honor/create_task.html
<html>
<head>
    <title>Create Task</title>
</head>
<body>
    <h2>Create a New Task</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Task</button>
    </form>
</body>
</html>

honor/templates/honor/index.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% load static %}
<link rel="stylesheet" href="{% static 'honor/style.css' %}">

<header>
    <div class = "top-banner"> </div>
    <img class = "logo" src= "{% static 'honor/images/Screenshot 2024-04-16 113934.png' %}"  alt="rotunda_logo"/>
    <ul>
      <li><a href='/honor/'>Sign Out</a></li>  
      
      <li><a href='/honor/submitted'>View Reports</a></li>
        <li><a href='/honor/report'>Submit Report</a></li>
      <li><a class="active" href="../home/">Home</a></li>      
    </ul>
</header>

<body>
{#<img style="width:100%;" src= "{% static 'honor/images/honor_committee.png' %}"  alt="rotunda"/>#}

<div class="slider">
  <div class="slides">
    <div id="slide-1">
      <img style="width:100%;" src= "{% static 'honor/images/honor_committee.png' %}"  alt="rotunda"/>
    </div>
    <div id="slide-2">
      <img style="width:100%;" src= "{% static 'honor/images/rotunda.jpeg' %}"  alt="rotunda"/>
    </div>
    <div id="slide-3">
      <img style="width:100%;" src= "{% static 'honor/images/students.jpeg' %}"  alt="rotunda"/>
    </div>
  </div>
</div>


<footer class=" text-white">
    <div class = "top-banner"> </div>
    <div class="container text-center"><br>
      <small>Copyright &copy; CS3240 <br> Author: A-32</small>
        <p> This site is for educational purposes and no data submitted is actually monitored or taken seriously</p>
    </div>
</footer>
</body>

honor/templates/honor/login.html
{# load the tag library #}
{% load bootstrap5 %}
{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# display django.contrib.messages as bootstrap alerts #}
{% bootstrap_messages %}

{% load static %}
{% load authorization %}
<link rel="stylesheet" href="{% static 'honor/style.css' %}">
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="x-ua-compatible" content = "IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>
            Django Google Sign-In
        </title>
    </head>
    <header>
        <div class = "top-banner"> </div>
        <div class = "bottom-banner">

            <img class = "logo" style="left: 0%;width:300px; top: 20px" src= "{% static 'honor/images/Screenshot 2024-04-16 113934.png' %}"  alt="rotunda_logo"/>
            <h1 class = "title" >Log-In Page</h1>
        </div>

    </header>

        {#        <div style="background-image: url('../../static/honor/images/rotunda_background_pic.jpg');background: #a4c6ff;">#}
{#        <img class="border border-5 border-dark w-25" src= "{% static 'honor/images/rotunda_background_pic.jpg' %}"  alt="rotunda"/>#}
<div style="background-color: white;">
    

    <div class = "main-picture">
        <img style="width:100%;" src= "{% static 'honor/images/uva_lawn_under_stars.jpg' %}"  alt="rotunda"/>
        <div class="overlay"></div>
            <div class="content">
                {% load socialaccount %}
                <h2>
                    Google Login
                </h2>
                <!--- #Citation: https://www.youtube.com/watch?v=yO6PP0vEOMc
                --->
                <a href="{% provider_login_url 'google' %}?next=/home">Log in with google</a>
    
                <br><br>
                <button onclick="location.href = '{% url 'honor:continue_anonymously'%}'">Anonymous</button>
    
            </div>
    </div>
</div>
<footer class=" text-white">
    {#<div style = "background-color: #232d49;">#}
        <div class = "top-banner"> </div>
        <div class="container text-center"><br>
          <small>Copyright &copy; CS3240 <br> Author: A-32</small>
            <p> This site is for educational purposes and no data submitted is actually monitored or taken seriously</p>
        </div>
    </footer>
</html>

honor/templates/honor/reportDisplay.html
{# load the tag library #}
{% load bootstrap5 %}
{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# display dijango.contrib.messages as bootstrap alerts #}
{% bootstrap_messages %}

{% load static %}
{% load authorization %}
{% load socialaccount %}
<link rel="stylesheet" href="{% static 'honor/style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Report Display</title>
</head>
{#<script>#}
{#    used to adjust width of text boxes so there isn't uneccessary space   #}
{#     window.onload = function() {#}
{#        adjustWidth(document.getElementsByClassName('longtext'));#}
{#    };#}
{##}
{#    function adjustWidth(inputs) {#}
{#        for (var i = 0; i < inputs.length; i++) {#}
{#            var input = inputs[i];#}
{#            if (!input.adjusted) {#}
{#                input.style.width = ((input.value.length + 6) * 8) + 'px';#}
{#                input.adjusted = true;#}
{#            }#}
{#        }#}
{#    }#}
{#</script>#}
<header>
        <div class = "top-banner"> </div>
            <img class = "logo"  src= "{% static 'honor/images/Screenshot 2024-04-16 113934.png' %}"  alt="rotunda_logo"/>
<ul>
  <li><a href='/honor/'>Sign Out</a></li>    
  <li><a class="active" href='/honor/submitted'>View Reports</a></li>
    <li><a href='/honor/report'>Submit Report</a></li>
  <li><a  href="/honor/home/">Home</a></li>
  
</ul>
</header>


<body>

{#<div style="background-image: url({% static 'honor/images/uva_lawn_under_stars_tall.jpg' %}); background-size: cover;">#}
   <div>
    <div class="report-container">
        <div class="reportDisplay">
            <div class="report-grid-1">
            <h2>User</h2>
            <h2>{{ report.timeStamp }}</h2>
            {% if report.status == 1 %}
                <h2 style="color:red"> {{report_status}}</h2>
            {% elif report.status == 2 %}
                <h2 style="color:yellow"> {{report_status}}</h2>
            {% elif report.status == 3 %}
                <h2 style="color:green"> {{report_status}}</h2>
            {% endif %}
            
                <div>
                    <b><label title="Name of the Offender">Name </label><br></b>
{#                {% if report.nameOfOffender %} {{ report.nameOfOffender }}{% else %} N/A{% endif %}#}
                    <input readonly title="Name of the Offender" type="text" name="nameOfOffender" id="nameOfOffender" value= "{% if report.nameOfOffender %} {{ report.nameOfOffender }}{% else %} N/A{% endif %} "><br>
                </div>
                <div>
                  <b><label title="Class the violation took place in">Class</label><br></b>
                <input readonly title="Class the violation took place in" type="text" name="className" id="className" value="{% if report.className %} {{ report.className }}{% else %} N/A{% endif %}"><br>
                </div>
                <div>
                    <b><label title="Location where the violation took place">Location</label><br></b>
                    <input readonly title="Location where the violation took place" type="text" name="location" id="location" value="{% if report.location %} {{ report.location }}{% else %} N/A{% endif %}"><br>

                </div>
            


                <div class = "report-file">
                    {% if report.file %}
{#                    <a href="{{ report.file.url }}" target="_blank">View File</a>#}
                    <embed src="{{ report.file.url }}" style="width:50%; height:auto">
                {% else %}
                    No File Uploaded
                {% endif %}
                </div>

            </div>
            <div class="report-grid-2">

              <div class="report-description">
                <b><label title="Description of the honor violation">Description</label><br></b>
                <textarea readonly title="Description of the honor violation" name="description" id="description" placeholder="{% if report.description %} {{ report.description }}{% else %} N/A{% endif %}" style="width:100%; height:200px;word-break:break-word;">{% if report.description %} {{ report.description }}{% else %} N/A{% endif %}</textarea><br>
{#                <input readonly class = "longText" type="text" name="description" id="txt" oninput="adjustWidth(this);"  value= "{% if report.description %} {{ report.description }}{% else %} N/A{% endif %}" >input<br>#}

                </div>
                <div class="report-add-info">
                    <b><label title="additional information about the violation">Extra Info </label><br></b>
                    <textarea readonly title="additional information about the violation" name="addInfo" id="addInfo" placeholder="{% if report.addInfo %} {{ report.addInfo }}{% else %} N/A{% endif %}" style="width:100%; height:200px;">{% if report.addInfo %} {{ report.addInfo }}{% else %} N/A{% endif %}</textarea><br>
{#                <input class = "longText" type="text" name="addInfo" id="addInfo" value="{% if report.addInfo %} {{ report.addInfo }}{% else %} N/A{% endif %}"><br>#}

                </div>
            </div>
        <br>
         <button onclick="location.href = '/honor/submitted'">Back</button><br><br>
         <button onclick="location.href = '{% url 'honor:reportEdit' report.id %}'">Edit Report</button><br><br>
        <button onclick="location.href = '{% url 'honor:delete_report' report.id %}'">Delete Report</button>
        </div>


    </div>
    <div class="report-container">
        <div class="reportDisplay">
            <form action = "{% url 'honor:add_admin_comments' report.id %}" method ="post" class="container-fluid" enctype="multipart/form-data">
                {% csrf_token %}
                <b>
                    <label>Admin Comments </label><br>
                </b>
                <textarea name="comments" id="comments" placeholder="{% if report.admin_comments %}{{ report.admin_comments }}{% else %}Admin Comments {% endif %}" style="width:100%; height:100px;word-break:break-word;"></textarea><br>
                <br>
                {% if user|in_group:"power-user"%}
                    <input type="submit" value="Submit">
                {% endif %}
            </form>
            <form action = "{% url 'honor:resolve' report.id %}" method ="post" class="container-fluid" enctype="multipart/form-data">
                    {% csrf_token %}
                <br>
                {% if user|in_group:"power-user"%}
                    <input type="submit" value="Resolved">
                {% endif %}
            </form>
        </div>
    </div>
<br><br>

</div>
    <footer class=" text-white">
    {#<div style = "background-color: #232d49;">#}
        <div class = "top-banner"> </div>
        <div class="container text-center"><br>
          <small>Copyright &copy; CS3240 <br> Author: A-32</small>
            <p> This site is for educational purposes and no data submitted is actually monitored or taken seriously</p>
        </div>
    </footer>
</body>
</html>

honor/templates/honor/reportEdit.html
{# load the tag library #}
{% load bootstrap5 %}
{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# display dijango.contrib.messages as bootstrap alerts #}
{% bootstrap_messages %}

{% load static %}
<link rel="stylesheet" href="{% static 'honor/style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Report Display</title>
</head>

{#<header>#}
{#    <div class = "top-banner"> </div>#}
{#    <div class = "bottom-banner">#}
{##}
{#        <a href="/honor/home/"> <img class = "logo" style="left: 0%;width:300px; top: 20px" src= "{% static 'honor/images/Screenshot 2024-04-16 113934.png' %}"  alt="rotunda_logo"/></a>#}
{#        <div class="banner" style="right:0;transform: translate(-25%, 60%);">#}
{#            [Editing Report]#}
{#        </div>#}
{#        <h1 class = "title" >Report #{{ report.id }}</h1>#}
{#    </div>#}
{##}
{##}
{#</header>#}
<header>
        <div class = "top-banner"> </div>
            <img class = "logo"  src= "{% static 'honor/images/Screenshot 2024-04-16 113934.png' %}"  alt="rotunda_logo"/>
{# <div class="banner" style="right:0;transform: translate(-25%, 60%);">#}
{#            [Editing Report]#}
{#        </div>#}
    <ul>
  <li><a href='/honor/'>Sign Out</a></li>    
  <li><a class="active" href='/honor/submitted'>View Reports</a></li>
    <li><a href='/honor/report'>Submit Report</a></li>
  <li><a  href="/honor/home/">Home</a></li>
  
</ul>
</header>

    <body>
<div>
    {% if error_message %}
                    <p class="error"><strong>
                        {{ error_message }}
                    </strong></p>
                    {% endif %}
    
        <div class="report-container">
            <div class="reportDisplay">
            <form action = "{% url 'honor:edit_report'  %}" method ="post" enctype="multipart/form-data">
            {% csrf_token %}
             
                <div class="report-grid-1">
                <h2>User</h2>
                <h2>[Editing Report]</h2>
                <h2>{{report_status}}</h2>
                 <input type="hidden" id="Id" name="Id" value="{{ report.id }}">
                    <div>
                        <b><label title="Name of the Offender">Name </label><br></b>
    {#                {% if report.nameOfOffender %} {{ report.nameOfOffender }}{% else %} N/A{% endif %}#}
                        <input title="Name of the Offender" type="text" name="nameOfOffender" id="nameOfOffender" value="{{ report.nameOfOffender }}"><br>
                    </div>
                    <div>
                      <b><label title="Class the violation took place in">Class</label><br></b>
                    <input title="Class the violation took place in" type="text" name="className" id="className" value="{{ report.className }}"><br>
                    </div>
                    <div>
                        <b><label title="Location where the violation took place">Location</label><br></b>
                        <input title="Location where the violation took place" type="text" name="location" id="location" value="{{ report.location }}"><br>
    
                    </div>
    
    
                    <div class = "report-file">
                        {% if report.file %}
    {#                    <a href="{{ report.file.url }}" target="_blank">View File</a>#}
                        <embed src="{{ report.file.url }}" style="width:50%; height:auto">
                    {% else %}
                        No File Uploaded
                    {% endif %}
                    </div>
    
                </div>
                <div class="report-grid-2">
    
                  <div class="report-description">
                    <b><label title="Description of the honor violation">Description</label><br></b>
                    <textarea title="Description of the honor violation" name="description" id="description"  style="width:100%; height:200px;word-break:break-word;">{{ report.description }}</textarea><br>
    {#                <input readonly class = "longText" type="text" name="description" id="txt" oninput="adjustWidth(this);"  value= "{% if report.description %} {{ report.description }}{% else %} N/A{% endif %}" >input<br>#}
    
                    </div>
                    <div class="report-add-info">
                        <b><label title="additional information about the violation">Extra Info </label><br></b>
                        <textarea title="additional information about the violation" name="addInfo" id="addInfo"  style="width:100%; height:200px;">{{ report.addInfo }}</textarea><br>
    {#                <input class = "longText" type="text" name="addInfo" id="addInfo" value="{% if report.addInfo %} {{ report.addInfo }}{% else %} N/A{% endif %}"><br>#}
    
                    </div>
                </div>
                <br><input type="submit" value="Submit"><br><br>
            
            </form>
             <button style="width:70px" onclick="location.href = '/honor/{{ report.id }}/reportDisplay'">Back</button>
            </div>
    
    
        </div>
    {#    <div class="report-container">#}
    {#        <div class="reportDisplay">#}
    {#            <form action = "{% url 'honor:add_admin_comments' report.id %}" method ="post" class="container-fluid" enctype="multipart/form-data">#}
    {#                {% csrf_token %}#}
    {#                <b>#}
    {#                    <label>Admin Comments </label><br>#}
    {#                </b>#}
    {#                <textarea name="comments" id="comments" placeholder="{% if report.admin_comments %}{{ report.admin_comments }}{% else %}Admin Comments {% endif %}" style="width:100%; height:100px;word-break:break-word;"></textarea><br>#}
    {#                <br><input type="submit" value="Submit">#}
    {#            </form>#}
    {#        </div>#}
    {#    </div>#}
    <br><br>
    </div>
    </body>

<footer class=" text-white">
    {#<div style = "background-color: #232d49;">#}
        <div class = "top-banner"> </div>
        <div class="container text-center"><br>
          <small>Copyright &copy; CS3240 <br> Author: A-32</small>
            <p> This site is for educational purposes and no data submitted is actually monitored or taken seriously</p>
        </div>
    </footer>
</html>

honor/templates/honor/socialapp_check.html
<!-- THIS PAGE IS FOR TESTING................ -->

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TEST VIEW</title>
</head>
<body>
    {% if google_app_exists %}
        <p>Google SocialApp exists!</p>
    {% else %}
        <p>Google SocialApp does not exist.</p>
    {% endif %}
</body>
</html>